apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: sky2108/idp-lab-app:4ec8be49a3bd3363e2aef492ce80724a8b94e405
        ports:
        - containerPort: 5000
