apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: sky2108/idp-lab-app:5261de7a45b43fe9b30f1a1204fe67934e5939f0
        ports:
        - containerPort: 5000
